### ISSUE TITLE
Today, the recording is stuck.

### ISSUE THREAD

**Issue by AvrilL161** [WhiteMinds/LiveAutoRecord#177] opened 2024-03-04 16:34 UTC
Today, the recording is stuck. Only the first 16 minutes of the broadcast were recorded.
And then even after the end of the broadcast the status was “recording”, until I manually pressed stop.
There were no network errors in the router logs.
![2024-03-04_19-16-43](https://github.com/WhiteMinds/LiveAutoRecord/assets/29428522/3eb4860c-9bcc-4445-88fe-ac25abd0ab36)
![2024-03-04_19-23-50](https://github.com/WhiteMinds/LiveAutoRecord/assets/29428522/1d799547-23d5-4ee1-9e79-6b61613ced35)

**Comment by WhiteMinds** [comment] 2024-03-07 02:34
This appears to be a bug, most likely caused by network fluctuations (at any endpoint such as the host, broadcaster, or intermediate server) that led to ffmpeg entering an abnormal state. Furthermore, LAR did not correctly identify this state, leading to the misconception that it was still recording.

To solve this bug, I first need to know what state ffmpeg has entered. You can turn on the debug mode switch, so that a ffmpeg.log will also be generated during recording. When the same problem occurs, you can upload that log for me to use for debugging.

BTW, are you Russian? Or Chinese?

![image](https://github.com/WhiteMinds/LiveAutoRecord/assets/9160743/6f831a7b-c6f0-4988-94b5-7aa10112badd)

**Comment by AvrilL161** [comment] 2024-03-07 05:24
> BTW, are you Russian? Or Chinese? Previously, I did not consider users from other countries using this software, so I did not add the i18n feature.

I'm Russian, from Russia.
Perhaps these errors are affected by my territorial distance from the douyin servers.
But still your application is the most stable of all.

if errors are repeated, I will send you logs.
Thank You!

**Comment by WhiteMinds** [comment] 2024-03-10 10:13
In the new version [v4.6.1](https://github.com/WhiteMinds/LiveAutoRecord/releases/tag/v4.6.1), an experimental fix has been made for this issue.

I will close this issue for now.

If you still encounter this problem in the new version, you can reopen this issue or create a new one.

**Closed by WhiteMinds** 2024-03-10 10:13 UTC
Labels: bug
